### ISSUE TITLE
Can't execute jar-file under Ubuntu

### ISSUE THREAD

**Issue by EthicalWeb** [kontalk/desktopclient-java#102]
Unfortunatly I can't execute the jar-file with Ubuntu.

```
java -jar KontalkDesktopApp.jar
 Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:66)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2610)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2634)
	at org.kontalk.util.CryptoUtils.removeCryptographyRestrictions(CryptoUtils.java:45)
	at org.kontalk.Kontalk.start(Kontalk.java:129)
	at org.kontalk.Kontalk.main(Kontalk.java:209)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
	... 6 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
	at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
	... 6 more
```

**Comment by abika** [comment]
Assuming you tried the Desktop Client version 3.1.2, what is the Java Runtime Engine you are using?

**Comment by abika** [comment]
Ping?

**Comment by EthicalWeb** [comment]
Sorry for not responding so fast.

Yes, I am trying the Desktop Client version 3.1.2. With this version of Java:

```
java version "1.7.0_131"
OpenJDK Runtime Environment (IcedTea 2.6.9) (7u131-2.6.9-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)
```

**Comment by daniele-athome** [comment]
[Software Dependencies](https://github.com/kontalk/desktopclient-java#software-dependencies):

> * Java 8 (Java Runtime Engine)
