### ISSUE TITLE
Can't open key archive

### ISSUE THREAD

**Issue by jhoc2000** [kontalk/desktopclient-java#114]
I'm trying to import my Kontalk account onto my Linux computer. I've downloaded and extracted the zip desktop zip file: KontalkDesktop-3.1.2.zip
I then change into the directory: KontalkDesktop-3.1.2
and try to run the Java file: ./KontalkDesktopApp.jar

The GUI appears but I get the Java output:

Feb. 25, 2020 6:30:47 PM org.kontalk.Kontalk start
INFO: --START, version: 3.1.2--
Feb. 25, 2020 6:30:47 PM org.kontalk.util.CryptoUtils removeCryptographyRestrictions
CONFIG: cryptography restrictions removal not needed
Feb. 25, 2020 6:30:48 PM org.kontalk.persistence.Database <init>
CONFIG: version: 5
Feb. 25, 2020 6:30:48 PM sun.awt.X11.XToolkit setBackingStoreType
CONFIG: The system property sun.awt.backingStore is not set, by default backingStore=NotUseful
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
	at java.base/java.lang.Class.getField(Class.java:1999)
	at com.alee.utils.ReflectUtils.getStaticFieldValue(ReflectUtils.java:630)
	at com.alee.utils.ProprietaryUtils.setupUIDefaults(ProprietaryUtils.java:92)
	at com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:536)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:932)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
	at org.kontalk.view.View.<init>(View.java:136)
	at org.kontalk.view.View.<init>(View.java:64)
	at org.kontalk.view.View$2.call(View.java:189)
	at org.kontalk.view.View$2.call(View.java:186)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/john/KontalkDesktop-3.1.2/lib/xstream-1.4.7.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Feb 25, 2020 6:30:49 PM org.kontalk.system.Control launch
INFO: no account found, asking for import...
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:247)
	at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
	at org.kontalk.view.ListView.access$500(ListView.java:75)
	at org.kontalk.view.ListView$8.run(ListView.java:358)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.kontalk.view.View.showImportWizard(View.java:358)
	at org.kontalk.view.View.updateOnEDT(View.java:257)
	at org.kontalk.view.View.access$500(View.java:64)
	at org.kontalk.view.View$4.run(View.java:244)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(DefaultRowSorter.java:496)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:247)
	at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
	at org.kontalk.view.ListView.access$500(ListView.java:75)
	at org.kontalk.view.ListView$8.run(ListView.java:358)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.kontalk.view.View.showImportWizard(View.java:358)
	at org.kontalk.view.View.updateOnEDT(View.java:257)
	at org.kontalk.view.View.access$500(View.java:64)
	at org.kontalk.view.View$4.run(View.java:244)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

The import wizard is show and I select next:
I enter the Kontalk_keys.zip file that I exported from my phone and the password and select next. I then get the error: Can't open key archive even though the pathname and file name are correct. The permissions on the file are: -rwxrwx-wx

### Additional information
Kontalk Desktop version: 3.1.2
Operating System: Ubuntu 19.04
Desktop Environment:  Mate 1.20.4
Kontalk Android version: 4.3.1

(For errors please check for exceptions or warnings in the log file and
include them here. More information: https://github.com/kontalk/desktopclient-java/wiki#i-found-a-bug-what-to-do )

Where's the log file so that I can provide any errors?

**Comment by daniele-athome** [comment]
Thanks for reporting. What version of Java are you using? For the moment the client has been tested on Java 8 only (it should work on 9 too *in theory*, but not 11 or 12).

**Comment by jhoc2000** [comment]
openjdk 11.0.4 2019-07-16

**Comment by daniele-athome** [comment]
Ok please try with Java 8.
