### ISSUE TITLE
Not working on ubuntu LTS v18

### ISSUE THREAD

**Issue by wibrt** [kontalk/desktopclient-java#115]
I guess this application is not working/not maintained any more?

HTH

### Additional information
Kontalk Desktop version: v3.1.2
Operating System: Ubuntu LTS v18
Desktop Environment:  Default Desktop Environment ubuntu LTS
Kontalk Android version:  4.3.1

after starting it with java -jar jarfilekontalk.jar
i was able to import the keys, but unable to connect,
let alone connect to xmpp users, which was the primary reason for testing this,
(as the regular kontalk app can only talk to kontalk app users)

### java log
```
 java -jar KontalkDesktopApp.jar
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
INFO: Setting language: nl
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_JSQ2
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_6P7W
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_769Q
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_M63K
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_S39E
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_53Z5
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_K94P
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_RYMX
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_X4K8
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_7MO0
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_B8XU
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_012T
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_VA0W
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_M91R
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_4QK9
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_XK4W
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_U1UW
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_IBU6
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_S8GI
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_WW4U
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_BWQV
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_MGHZ
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_CYIK
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_9NTE
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_1SED
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_D0BD
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_G3C7
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_PDYT
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_052Y
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_OUKY
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_AOG4
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_8GRW
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_45P5
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_AW5R
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_ELUO
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_4ZBG
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_HAK6
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_MD21
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_ZKM0
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_FSGV
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_Z35B
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_D7B3
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_O85V
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_UEN4
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_LQ9X
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_92KK
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_0R7Z
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_6AKS
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_YNOC
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_7BO5
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_ZN6V
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_WVG1
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_6OKN
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_A812
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_CAM4
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_4N5N
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_YV5S
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_QNRV
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_IGQC
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_Z91J
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_B7RA
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_SFU0
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_T3V1
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_H3ZD
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_N3SN
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_AZFE
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_J4BM
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_403J
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_LK8U
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_AUZG
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_CQEO
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_1PWT
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.Tr init
WARNING: key in translation but not in key file: s_SS8P
mrt. 29, 2020 12:27:36 P.M. org.kontalk.Kontalk start
INFO: --START, version: 3.1.2--
mrt. 29, 2020 12:27:36 P.M. org.kontalk.util.CryptoUtils
removeCryptographyRestrictions
CONFIG: cryptography restrictions removal not needed
mrt. 29, 2020 12:27:37 P.M. org.kontalk.persistence.Database <init>
CONFIG: version: 5
mrt. 29, 2020 12:27:37 P.M. sun.awt.X11.XToolkit setBackingStoreType
CONFIG: The system property sun.awt.backingStore is not set, by default
backingStore=NotUseful
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
        at java.base/java.lang.Class.getField(Class.java:1999)
        at
com.alee.utils.ReflectUtils.getStaticFieldValue(ReflectUtils.java:630)
        at
com.alee.utils.ProprietaryUtils.setupUIDefaults(ProprietaryUtils.java:9
2)
        at
com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:5
36)
        at
java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicL
ookAndFeel.java:150)
        at
java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
        at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:932)
        at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
        at org.kontalk.view.View.<init>(View.java:136)
        at org.kontalk.view.View.<init>(View.java:64)
        at org.kontalk.view.View$2.call(View.java:189)
        at org.kontalk.view.View$2.call(View.java:186)
        at
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
com.thoughtworks.xstream.core.util.Fields
(file:/home/els/Bureaublad/KontalkDesktop-3.1.2/lib/xstream-1.4.7.jar)
to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of
com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further
illegal reflective access operations
WARNING: All illegal access operations will be denied in a future
release
Mar 29, 2020 12:27:38 PM org.kontalk.view.TrayManager setTray
INFO: tray icon not supported
Mar 29, 2020 12:27:38 PM org.kontalk.client.Client connect
CONFIG: connecting...
Exception in thread "main" java.lang.NullPointerException: No password
supplied for PKCS#12 KeyStore.
        at
org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engi
neLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at
org.kontalk.util.TrustUtils.getTrustStore(TrustUtils.java:154)
        at
org.kontalk.util.TrustUtils.getCustomSSLContext(TrustUtils.java:105)
        at
org.kontalk.util.TrustUtils.getCustomSSLContext(TrustUtils.java:94)
        at
org.kontalk.client.KonConnection.buildConfiguration(KonConnection.java:
123)
        at
org.kontalk.client.KonConnection.<init>(KonConnection.java:70)
        at org.kontalk.client.Client.connect(Client.java:139)
        at
org.kontalk.system.Control$ViewControl.connect(Control.java:681)
        at
org.kontalk.system.Control$ViewControl.connect(Control.java:673)
        at org.kontalk.system.Control.launch(Control.java:148)
        at org.kontalk.Kontalk.start(Kontalk.java:153)
        at org.kontalk.Kontalk.main(Kontalk.java:209)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for
length 0
        at
java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToView(Default
RowSorter.java:496)
        at
java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2607)
        at
java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4180)
        at
java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4121)
        at
java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Abst
ractTableModel.java:297)
        at
java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(
AbstractTableModel.java:247)
        at org.kontalk.view.ListView.updateOnEDT(ListView.java:367)
        at org.kontalk.view.ListView.access$500(ListView.java:75)
        at org.kontalk.view.ListView$8.run(ListView.java:358)
        at
java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.ja
va:313)
        at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native
Method)
        at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doInter
sectionPrivilege(ProtectionDomain.java:85)
        at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventD
ispatchThread.java:203)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDisp
atchThread.java:124)
        at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventD
ispatchThread.java:113)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:109)
        at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThrea
d.java:101)
        at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:
90)
```

**Comment by daniele-athome** [comment]
Please ensure you are using Java 8.

**Comment by wibrt** [comment]
Solution:
Indeed, the java client starts using Java 8.

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar KontalkDesktopApp.jar

________________________________
Van: Daniele Ricci <notifications@github.com>
Verzonden: maandag 30 maart 2020 18:26
Aan: kontalk/desktopclient-java <desktopclient-java@noreply.github.com>
CC: Wim Bertels <wim.bertels@ucll.be>; Author <author@noreply.github.com>
Onderwerp: Re: [kontalk/desktopclient-java] Not working on ubuntu LTS v18 (#115)


Please ensure you are using Java 8.
