### ISSUE TITLE
Not responding to switching contacts and enter keys

### ISSUE THREAD

**Issue by ffami** [kontalk/desktopclient-java#58]
I have kontalk desktop v 3.0.3 from git updated to latest changes as of tonight on Debian Sid. Compile done with openjdk-8-jdk. Opens up and I could import my keys but interface is not responding as in hangs up when I try to move between contact names. Multiple selections turn up out of no where. I cannot enter key to send messages. Debug.log has no errors. It is connecting to beta.kontalk.net and refreshing keys.

I am always using ./gradlew run to start the application and it stops at "> Building 87% > :run" on terminal while its running. That's strange.

**Comment by abika** [comment]
> I have kontalk desktop v 3.0.3

3.0.3 or 3.0.4?

> Opens up and I could import my keys but interface is not responding as in hangs up when I try to move between contact names.

You mean when you change the selection in the contact list (with mouse or keyboard)?

> Multiple selections turn up out of no where.

Selections or contacts? The Desktop client automatically syncs with the contact list (=roster) on the server.

> I am always using ./gradlew run to start the application and it stops at "> Building 87% > :run" on terminal while its running. That's strange.

This is normal. Gradle treats the "run" target as completed when its done (i.e. when the app terminates). 

I couldn't reproduce this. Are there any exceptions or "WARNING"s written to the console output?

**Comment by ffami** [comment]
Hi @abika. Version shows 3.0.3. I am trying to change using mouse. By selections I mean to say contacts are highlighted. No duplicity. 

I ran with --stacktrace and found an exception message.  Hope this helps.

22:40:58|INFO  |org.kontalk.Kontalk start---START, version: 3.0.3--
22:40:58|CONFIG|org.kontalk.util.CryptoUtils removeCryptographyRestrictions-cryptography restrictions removal not needed
22:40:59|CONFIG|sun.awt.X11.XToolkit setBackingStoreType-The system property sun.awt.backingStore is not set, by default backingStore=NotUseful
22:41:02|CONFIG|org.kontalk.system.Database <init>-version: 3
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at org.kontalk.view.Table$TableRenderer.getTableCellRendererComponent(Table.java:370)
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7031)
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7418)
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6933)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:497)
	at javax.swing.JTable.addRowSelectionInterval(JTable.java:2193)
	at com.alee.laf.table.WebTable.addSelectedRow(WebTable.java:100)
	at com.alee.laf.table.WebTable.setSelectedRow(WebTable.java:88)
	at com.alee.laf.table.WebTable.setSelectedRow(WebTable.java:82)
	at org.kontalk.view.Table.setSelectedItem(Table.java:231)
	at org.kontalk.view.ChatListView.selectLastChat(ChatListView.java:136)
	at org.kontalk.view.View$1.run(View.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:697)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at jaEventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by abika** [comment]
Something is not right. Current master is at 3.0.4, you should be at this version too. Please make sure youre at the latest HEAD.

Anyway,
```
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
at org.kontalk.view.Table$TableRenderer.getTableCellRendererComponent(Table.java:370)
```
indeed, `table` and `value` arguments can be null. Looks like this is only triggered on certain platforms (Gnome/ATK(?)). If not fixed, please reopen.

And thanks for reporting.
