### ISSUE TITLE
Cannot import key from android kontalk

### ISSUE THREAD

**Issue by callmemagnus** [kontalk/desktopclient-java#6]
I tried to import my keys export from the android app:

I get Import process finished with: Error

Tested multiple times in order to reduce the chance of the passphrase to be wrongly typed

The exception:

```
Sep 17, 2014 10:03:26 PM org.kontalk.model.Account importAccount
WARNING: can't load personal key
org.bouncycastle.openpgp.PGPException: invalid key: Illegal key size
    at org.bouncycastle.openpgp.operator.jcajce.JcePBESecretKeyDecryptorBuilder$1.recoverKeyData(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.extractKeyData(Unknown Source)
    at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
    at org.kontalk.crypto.PersonalKey.load(PersonalKey.java:187)
    at org.kontalk.model.Account.importAccount(Account.java:100)
    at org.kontalk.view.ImportDialog.importAccount(ImportDialog.java:195)
    at org.kontalk.view.ImportDialog.updatePage(ImportDialog.java:170)
    at org.kontalk.view.ImportDialog.switchPage(ImportDialog.java:153)
    at org.kontalk.view.ImportDialog.access$000(ImportDialog.java:48)
    at org.kontalk.view.ImportDialog$2.actionPerformed(ImportDialog.java:98)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
    at java.awt.Dialog.show(Dialog.java:1082)
    at java.awt.Component.show(Component.java:1655)
    at java.awt.Component.setVisible(Component.java:1607)
    at java.awt.Window.setVisible(Window.java:1014)
    at java.awt.Dialog.setVisible(Dialog.java:1005)
    at org.kontalk.view.View.showImportWizard(View.java:306)
    at org.kontalk.view.View.handleException(View.java:296)
    at org.kontalk.Kontalk.handleException(Kontalk.java:209)
    at org.kontalk.Kontalk.connect(Kontalk.java:156)
    at org.kontalk.view.View.connect(View.java:314)
    at org.kontalk.view.MainFrame$3.actionPerformed(MainFrame.java:129)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.menuDragMouseReleased(BasicMenuItemUI.java:943)
    at javax.swing.JMenuItem.fireMenuDragMouseReleased(JMenuItem.java:585)
    at javax.swing.JMenuItem.processMenuDragMouseEvent(JMenuItem.java:482)
    at javax.swing.JMenuItem.processMouseEvent(JMenuItem.java:428)
    at javax.swing.MenuSelectionManager.processMouseEvent(MenuSelectionManager.java:322)
    at javax.swing.plaf.basic.BasicPopupMenuUI$MouseGrabber.eventDispatched(BasicPopupMenuUI.java:869)
    at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2444)
    at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2336)
    at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2294)
    at java.awt.Component.dispatchEventImpl(Component.java:4768)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1024)
    at javax.crypto.Cipher.init(Cipher.java:1345)
    at javax.crypto.Cipher.init(Cipher.java:1282)
    ... 101 more
```

**Comment by workpanda** [comment]
Hi. I have found as below  when importing the security key to decode.

6460-6460/secure.com.pgpendeapp W/System.err﹕ org.bouncycastle.openpgp.PGPException: Exception creating cipher
08-26 22:02:00.487    6460-6460/secure.com.pgpendeapp W/System.err﹕ at org.bouncycastle.openpgp.PGPSecretKey.extractKeyData(Unknown Source)
08-26 22:02:00.513    6460-6460/secure.com.pgpendeapp W/System.err﹕ at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
08-26 22:02:00.540    6460-6460/secure.com.pgpendeapp W/System.err﹕ at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
08-26 22:02:00.552    6460-6460/secure.com.pgpendeapp W/System.err﹕ at EncryptUtils.PGPUtils.findSecretKey(PGPUtils.java:192)
08-26 22:02:00.564    6460-6460/secure.com.pgpendeapp W/System.err﹕ at EncryptUtils.PGPUtils.decryptFile(PGPUtils.java:229)
08-26 22:02:00.573    6460-6460/secure.com.pgpendeapp W/System.err﹕ at EncryptUtils._PGPFileProcessor.decrypt(_PGPFileProcessor.java:37)
08-26 22:02:00.580    6460-6460/secure.com.pgpendeapp W/System.err﹕ at secure.com.pgpendeapp.MainActivity.onClick(MainActivity.java:199)

**Comment by daniele-athome** [comment]
I'm sorry @workpanda how is that related to Kontalk?
Anyway without a cause it's hard to say. It could be strong cipher restrictions though.

**Comment by workpanda** [comment]
Hi, thanks for your reply.
sorry, I need to know which tool I need for PGP Tools in windows 8.
so I can generate PGP public/private key and test the code correctly.
thanks again.

**Comment by workpanda** [comment]
I am signing a file  with pgp private key.
but I have found the error when getting the secret key.
please quote me.
thanks.

public static PGPSecretKey readSecretKey(
            InputStream in)
            throws IOException, PGPException
    {
        Security.addProvider(new BouncyCastleProvider());
        InputStream keyIn = PGPUtil.getDecoderStream(in);

        PGPSecretKeyRingCollection pgpSec = new PGPSecretKeyRingCollection(keyIn);

        //
        // we just loop through the collection till we find a key suitable for encryption, in the real
        // world you would probably want to be a bit smarter about this.
        //
        PGPSecretKey    key = null;

        //
        // iterate through the key rings.
        //
        Iterator rIt = pgpSec.getKeyRings();

        while (key == null && rIt.hasNext())
        {
            PGPSecretKeyRing kRing = (PGPSecretKeyRing)rIt.next();
            Iterator            kIt = kRing.getSecretKeys();

            while (key == null && kIt.hasNext())
            {
                PGPSecretKey    k = (PGPSecretKey)kIt.next();

                if (k.isSigningKey())
                {
                    key = k;
                }
            }
        }

        if (key == null)
        {
            throw new IllegalArgumentException("Can't find signing key in key ring.");
        }

        return key;
    }

09-01 01:01:18.086  30454-32184/com.opvw.videorecordapp W/System.err﹕ org.bouncycastle.openpgp.PGPException: org.bouncycastle.openpgp.PGPPublicKeyRing found where PGPSecretKeyRing expected
09-01 01:01:18.086  30454-32184/com.opvw.videorecordapp W/System.err﹕ at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
09-01 01:01:18.086  30454-32184/com.opvw.videorecordapp W/System.err﹕ at Services.EncryptUtils.PGPFileSignProcessor.readSecretKey(PGPFileSignProcessor.java:47)
09-01 01:01:18.086  30454-32184/com.opvw.videorecordapp W/System.err﹕ at Services.EncryptUtils.PGPFileSignProcessor.signFile(PGPFileSignProcessor.java:144)

**Comment by daniele-athome** [comment]
@workpanda I think you should write to a Bouncy Castle mailing list: https://www.bouncycastle.org/mailing_lists.html they will be able to help more over there.
