### ISSUE TITLE
"Unsupported major.minor version 52.0"

### ISSUE THREAD

**Issue by agharbeia** [kontalk/desktopclient-java#72]
I tried to run KontalkDesktop-3.1.1/KontalkDesktopApp.jar 
and I got:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/kontalk/Kontalk : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

On Ubuntu 14.04.05 on Linux 4.2.0-35-generic
and
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

**Comment by daniele-athome** [comment]
Kontalk needs Java 8 to run.
https://github.com/kontalk/desktopclient-java#software-dependencies

**Comment by abika** [comment]
>Error message: "Unsupported major.minor version 52.0"
>Reason: Java 8 required

Why can't they make error messages a bit more useful?
