### ISSUE TITLE
Unsatisfied link error (sqlite)

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/desktopclient-java#9]
On startup:

```
     [java] Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
     [java]     at org.sqlite.core.NativeDB._open(Native Method)
     [java]     at org.sqlite.core.DB.open(DB.java:161)
     [java]     at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
     [java]     at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
     [java]     at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
     [java]     at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
     [java]     at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
     [java]     at org.sqlite.JDBC.createConnection(JDBC.java:114)
     [java]     at org.sqlite.JDBC.connect(JDBC.java:88)
     [java]     at java.sql.DriverManager.getConnection(DriverManager.java:664)
     [java]     at java.sql.DriverManager.getConnection(DriverManager.java:208)
     [java]     at org.kontalk.system.Database.<init>(Database.java:73)
     [java]     at org.kontalk.system.Database.initialize(Database.java:295)
     [java]     at org.kontalk.Kontalk.start(Kontalk.java:119)
     [java]     at org.kontalk.Kontalk.main(Kontalk.java:165)
```

Application window shows, but I can't connect. I know you're developing, please tell me if I should stop reporting :-)

**Comment by abika** [comment]
Most likely already reported [here](https://bitbucket.org/xerial/sqlite-jdbc/issue/152/387-version-linux-issue). Downgraded sqlite-jdbc with e4052e2ca2cf89e674e9a749e692c622363182b6 . Can you test it again, please? And what platform are you using?

> I know you're developing, please tell me if I should stop reporting :-)

No! I specially need bug reports like these: Even with Java there are platform specific errors, can't test everything myself

**Comment by daniele-athome** [comment]
It's working now. I'm on Linux. Do you want to keep this issue open?

**Comment by abika** [comment]
thanks!
