### ISSUE TITLE
Default-jre not working

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/desktopclient-java#93]
Hi, i've got debian jessie with default-jre installed and i can't start Kontalk
`~/Programs/KontalkDesktop-3.1.1$ java -jar KontalkDesktopApp.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/kontalk/Kontalk : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
`

**Comment by webratte** [comment]
If I'm right the default-jre on jessie is openjdk-7-jre.

But Kontalk needs Java 8.

See also:
https://github.com/kontalk/desktopclient-java

**Comment by abika** [comment]
yes, Java 8 is required -> https://github.com/kontalk/desktopclient-java#software-dependencies

**Comment by OffifialMITX** [comment]
Oh, sorry, haven't seen it before.
